audit_header: false
title: Philadelphia Real Estate Video Blog with Jeremy Bowers
description: >-
  Jeremy Bowers, a top Real Estate Agent in Philadelphia, shares his own
  internal real estate agent training for free. His Real Estate Training, Tips
  and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title: KW Results
    url: /kw-results/
  - title: Training
    url: /training/
  - title: Culture
    url: /culture/
  - title: Office Tours
    url: /office-tours/
  - title: Freebies
    url: /freebies/
  - title: Upcoming Events
    url: /events/
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: 10 Step Marketing Plan
    url: 'https://s3.amazonaws.com/vyralmarketing/Jeremy+Bowers/10+Step+Marketing+Plan.pdf'
client:
  name: Jeremy Bowers
  title: Team Leader/CEO
  license_number:
  about_markdown: >-
    We understand that buying or selling a home is more than just a transaction:
    it’s a life-changing experience. That’s why our team of highly-seasoned real
    estate professionals is dedicated to providing exceptional, personalized
    service for all of our clients. We take great pride in the relationships we
    build and always work relentlessly on the client’s behalf to help them
    achieve their real estate goals.


    Our team of experts represents the best and brightest in the industry, and
    we’re always striving to lead the field in research, innovation, and
    consumer education. Today’s buyers and sellers need a trusted resource that
    can guide them through the complex world of real estate. With our extensive
    knowledge and commitment to providing only the best and most timely
    information to our clients, we are your go-to source for real estate
    industry insight and advice.
  brand: Keller Williams Philly
  brokerage:
  market: Philadelphia
  address: >-
    728 South Broad Street Fl 3<br>Philadelphia PA 19146<br><br>2401 Walnut
    Street, 6th floor<br>Philadelphia PA 19103
  phone: 484-243-0971
  phone_type: Office
  phone2: 215-370-9107
  phone2_type: Cell
  email: jeremycbowers@kw.com
  url: 'http://PhillyKW.com'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Free Strategy Call
    CTA_text: Get step by step guidance to help you sell more homes in less time.
    CTA_link_text: Schedule a Free Consultation
    CTA_url: 'https://calendly.com/jeremybowers/call-with-jeremy-bowers/01-10-2019'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/jeremybowerscoaching/'
  linkedin_url: 'https://www.linkedin.com/in/jeremybowers1/'
  youtube_url: 'https://www.youtube.com/channel/UCLxIbqfz7mhxwPWENY3O0KQ'
  twitter_url: 'https://twitter.com/thejeremybowers'
  instagram_url: 'https://www.instagram.com/thephillyrealestatecoach/'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Philadelphia Real Estate Podcast with Jeremy Bowers
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the
    Philadelphia Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Keller Williams Philly - your
    professional Philadelphia Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Philadelphia,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jeremy Bowers
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: 'Philadlephia’s # 1 Real Estate Training and Brokerage<br>by Jeremy Bowers'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c51f22'
  theme_color: '#47484a'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
